export const LOST_REPORT_STATUSES = {
  SUBMITTED: "SUBMITTED",
  UNDER_REVIEW: "UNDER_REVIEW",
  REVISION_REQUESTED: "REVISION_REQUESTED",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  MATCHED: "MATCHED",
  RETURNED: "RETURNED",
  CLOSED: "CLOSED",
} as const;

export type LostReportStatus = typeof LOST_REPORT_STATUSES[keyof typeof LOST_REPORT_STATUSES];

export const EDITABLE_STATUSES: LostReportStatus[] = [
  LOST_REPORT_STATUSES.SUBMITTED,
  LOST_REPORT_STATUSES.REVISION_REQUESTED,
];
